### ISSUE TITLE
`MethodError: no method matching nameof(::Type{Union{Missing, String}})`

### ISSUE THREAD

**Issue by ericphanson** [beacon-biosignals/TransformSpecifications.jl#25]
Urg, my bad. I suggested `nameof` in #19 but it turns out it doesn't handle things like unions, as I found out when upgrading and regenerating my diagram. I am not sure the right solution!

**Comment by ericphanson** [comment]
On #helpdesk on the Julia slack, user `@Chris` had the great suggestion to set `compact` to true, e.g. `sprint(print, T; context=:compact=>true)` gives a string without qualified names.

I took a look at the printing internals and this seems to work, since `isvisible` is only called within a block that's turned off for compact printing: https://github.com/JuliaLang/julia/blob/572fa5055ecb709edd3d227a10b46549f82b72b2/base/show.jl#L1039-L1044

I think we should use this for now, and I'll file a feature request to have a Base API to give us this

**Comment by hannahilea** [comment]
love it! i agree.
